### ISSUE TITLE
error is running the znz-segment-buildingfootprint-20190108-alldata code

### ISSUE THREAD

**Issue by mehran66** [daveluo/zanzibar-aerial-mapping#3]
When I run the following line of code:

learn.fit_one_cycle(10, max_lr=lr, callbacks=[SaveModelCallbackVerbose(learn, monitor='dice', mode='max', name='20190108-rn34unet-comboloss-alldata-512-best')])

I get the following error:
TypeError: __init__() got an unexpected keyword argument 'monitor'

**Comment by AhmadAmmar** [comment]
Change `SaveModelCallbackVerbose` to `SaveModelCallback`.

**Comment by daveluo** [comment]
Apologies for the very late reply. @AhmadAmmar's solution is correct (thanks!). This issue was caused by version updates to the fastai library (which also negated the need for a custom `SaveModelCallbackVerbose` because in the latest version, `SaveModelCallback` reports the monitored value and model checkpoint saving by default).
